-- SQL DB creation and startup
DROP DATABASE IF EXISTS attend;
CREATE DATABASE attend;
CREATE USER IF NOT EXISTS 'ATTEND_USER'@'localhost' IDENTIFIED BY 'PASSWORD';
GRANT ALL PRIVILEGES ON attend.* TO 'ATTEND_USER'@'localhost';
FLUSH PRIVILEGES;
